package.json
=> fix: [ONP-257]: run stamp script in bash

src/components/MultiTypeInput/MultiTypeInput.tsx
=> fix: [PIE-1755]: MultiTypeInput - Prevent the click event when enter key pressed in InputGroup

src/components/Page/PageSpinner.css
**Summary:**
Border-radius fix for PageSpinner 
**JIRA:**
https://harness.atlassian.net/browse/PL-15054
**Screenshots:**
Before (no border-radius with Spinner on top of parent-component):
After (added border-radius with Spinner on top of parent-component):
=> fix: [PL-15054]: border-radius fix for PageSpinner

src/components/Modal/ModalContext.ts, src/components/Modal/__tests__/modal.test.tsx
=> feat: remove error throw from useModal

src/components/FormikForm/FormikForm.css, src/components/FormikForm/FormikForm.tsx
**Summary**
Center align Placeholder of tags component
**Jira Links:**
https://harness.atlassian.net/browse/PL-20548
**Screenshots:**
**Before:**
**After:**
**Before:**
**After:**
=> fix: [PL 20548]: Center align Placeholder of tags component

src/components/FormikForm/FormikForm.css
=> fix: [PIE-2227]: spacing for Multiselect inside of FormikForm

src/components/ThumbnailSelect/ThumbnailSelect.tsx
Currently because tooltip prop does not have string as one of the type, typescript throws error while passing string values.
Internally, ThumbnailSelect component does make use of string tooltip value and displays tooltip. But, no consumer can pass string values which makes functionality non-usable.
JIRA - https://harness.atlassian.net/browse/PIE-2265
=> fix: [PIE-2265]: allow string as other tooltip type in ThumbnailSelect component

src/components/MultiTypeInput/MultiTypeInput.tsx
=> feat: [PIE-1735]: Git Commit the fix for multitype on firefox/safari

src/styles/blueprint-overrides.css, src/styles/modal.css
**Summary:**
An old JIRA focussed on fixing this issue at a single place: https://harness.atlassian.net/browse/PL-21194
With this PR, Fixed Dialog Resizing Issue everywhere
**Jira Links:**
https://harness.atlassian.net/browse/PL-22559
**Screenshots:**
Before:
After:
=> fix: [PL-22559]: Fixed Dialog Resizing Issue at multiple places

src/styles/modal.css
Summary:
This dialog resizing bug was introduced with this PR: https://github.com/harness/uicore/pull/591 meant to fix it for wider dialogs.
Added `min-width` to fix this for narrower dialogs that rely on default value from Blueprint library.
Default width in blueprint library is 500px. "min-width" prevents any wider dialog from going below this value
JIRA:
https://harness.atlassian.net/browse/PL-23050
Screenshots:
Before:
After:
=> fix: [PL-23050]: Fixed dialog width

src/components/Dialog/Dialog.css, src/styles/modal.css
**Summary:**
Left border is visible in Modals. Both Anjan's and Maddy's [changes](https://github.com/harness/harness-core-ui/commit/699b022fe025d4fa866e1ba2da02a4be1a8f9030) are causing this. Anjan's changes have been around for 2 years (check src/modules/cv/components/MetricsVerificationModal/MetricsVerificationModal.module.scss in the commit)
With GLOBAL and !important—these changes overrode [Maddy's changes](https://github.com/harness/uicore/commit/edbfef8b43756e648e870cd78e73bb29fa369024).
Now that Anjan has moved the CSS from global to local [in this commit](https://github.com/harness/harness-core-ui/commit/06a46bcfaac9822fe4bad89afbe71b36f5d0a431), Maddy's changes are visible.
This PR is an undo of Maddy's changes
**JIRA:**
https://harness.atlassian.net/browse/PL-23087 …
=> fix: [PL-23087]: Removed left border from modals

src/components/Container/Container.tsx, src/layouts/Layout.tsx
=> fix: display names for layouts and container

src/components/MultiTypeInput/MultiTypeInput.tsx, src/components/Select/Select.css
=> fix: [PIE-2699]: portal select popover has no styling

src/components/MultiTypeInput/MultiTypeInput.css
**Before fix : 1px space can be seen on top and bottom around the separation between icon and input area**
**After fix ---->** 
=> fix: [PIE-1661]: height fixed for multi type input icon

src/components/FormikForm/__tests__/FormikForm.test.tsx, src/components/FormikForm/__tests__/__snapshots__/FormikForm.test.tsx.snap, src/components/Select/Select.css, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
**Summary:**
Added tooltip for the ability to see the full name of a lengthy tag (Note: this is NOT the Blueprint Tag-Input component)
**Jira Links:**
https://harness.atlassian.net/browse/PL-21624
**Screenshots:**
Before:
After:
=> fix: [PL-21624]: added tooltip for the ability to see the full name of a lengthy tag

src/components/MultiTypeInput/MultiTypeInput.tsx
This change would enable us to support list of expressions in platform ---> 
['<+pipeline.name>', '<+pipeline.type>']
=> fix: [PIE-2757]: adds support for list of expressions in util

src/components/ConfirmDialog/ConfirmationDialog.tsx, src/components/ConfirmDialog/useConfirmationDialog.tsx
…se and canEscapeKeyClose props to useConfirmationDialog
=> Add support for showcloseButton, canOutsideClickClose and canEscapeKeyClose props to useConfirmationDialog

src/components/ConfirmDialog/ConfirmationDialog.tsx, src/components/ConfirmDialog/useConfirmationDialog.tsx
=> fix: [PIE-3247]: Show cancel button if cancelButtonText is there

src/components/MultiTypeInput/MultiTypeInput.tsx
Summary -
Making multi type logic backward compatible, by default it follows the old behaviour, so that changes are not required in the CI etc files.
The boolean can be used to apply the list of expressions behaviour for all the newly added components
=> fix: [PIE-3456]: making multi type logic backward compatible

src/components/Select/Select.css, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
Added a borderless prop to core Select input component.
Also, optimized "Nothing Found" condition.
=> feat: [PIE-3667]: Add borderless prop to Select input

src/_stories/components/Colors.tsx
`--purple-500` is a duplicate of `--purple-600`, and differs from the UX team's Figma palette. Fixes `--purple-500` to match
=> fix: [STO-4451]: Match --purple-500 to UX Figma palette

src/components/Modal/ModalErrorHandler.tsx
https://harness.atlassian.net/browse/PL-25033
BEFORE
AFTER
=> fix: [PL-25033]: Wrap words in ModalErrorHandler

src/components/FormikForm/FormikForm.tsx
This PR fixes an issue whereby the `usePortal` prop of the `FormInput.Select` component was passed to the `FormGroup` component instead of the `Select` component.
Refs [PL-25566](https://harness.atlassian.net/browse/PL-25566)
=> chore: [PL-25566]: Move usePortal prop to Select component

packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
This PR switches from using a purely CSS trick to display scroll indicators in the ModalDialog component to using an event-triggered solution. The purely CSS version unfortunately displayed the scroll indicator below the content.
|Before|After|
|------|------|
|![Before](https://user-images.githubusercontent.com/7167253/172205021-a57a17f4-a023-4583-8a35-afc237c4105f.png)|![After](https://user-images.githubusercontent.com/7167253/172205106-05480837-36c8-4756-9e28-77de073547a0.png)|
Refs [PL-25618](https://harness.atlassian.net/browse/PL-25618)
=> fix: [PL-25618]: Ensure scroll indicators are above content

packages/uicore/package.json, packages/uicore/webpack.config.js, yarn.lock
We were using `webpack-node-externals` package to mark any dependencies which are external. This works well for a repo where the modules are not hoisted, but not in a monorepo setup, as it checks for `node_modules` at the same level as the config file. Hence we need to handle it ourselves now.
=> fix: externals config in webpack

packages/uicore/src/components/InputWithIdentifier/InputWithIdentifier.tsx
Docs team wants every ID component on UI  to have the same Tooltip. For this we added  constantTooltipID for ID component
=> feat: [PL-25668]: Universal tooltipid for all id component

packages/uicore/src/components/PillToggle/PillToggle.css, packages/uicore/src/components/PillToggle/PillToggle.stories.tsx, packages/uicore/src/components/PillToggle/PillToggle.tsx, packages/uicore/src/components/PillToggle/__tests__/PillToggle.test.tsx, packages/uicore/src/components/PillToggle/__tests__/__snapshots__/PillToggle.test.tsx.snap, packages/uicore/src/components/VisualYamlToggle/VisualYamlToggle.tsx
JIRA - https://harness.atlassian.net/browse/CDS-38820
Design Link: https://www.figma.com/file/4cqisYyQGDjzz51LyDp0Wj/Config-as-Code?node-id=3568%3A27734
Design image: 
**After Dev**
Storybook screenshot:
=> feat: [CDS-38820]: provide props in PillToggle component so that consumers show disable warning icon and tooltip

packages/uicore/src/components/SplitButton/SplitButton.css
=> fix: add display flex to SplitButton

packages/uicore/src/components/SplitButton/SplitButton.css, packages/uicore/src/components/SplitButton/SplitButton.tsx
=> fix: pass tooltipProps to second button only in SplitButton component

packages/uicore/src/components/SplitButton/SplitButton.css, packages/uicore/src/components/SplitButton/SplitButton.tsx
=> fix: SplitButton css specificity for secondary variation

packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.stories.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
This PR changes from triggering `manageScrollIndicators` on opening of the modal to triggering using `useLayoutEffect` to ensure that the action is triggered whenever the display of the body changes.
|Before|After|
|------|------|
|![Before](https://user-images.githubusercontent.com/7167253/176883192-f3bc0d93-7acd-4c7b-9c09-59f6fdf7d4c3.mp4)|![After](https://user-images.githubusercontent.com/7167253/176883233-655fb598-c23a-4f21-ab04-15c30ff9bec0.mp4)|
Refs [PL-26179](https://harness.atlassian.net/browse/PL-26179)
=> fix: [PL-26179]: Ensure overflow indicator management triggered when content changes

packages/icons/src/Options.svg
Made the dots smaller and more spaced out for `Options` button
=> chore: [FFM-3975]: smaller and more spaced out dots for options button

packages/uicore/src/components/TableV2/TableV2.tsx
- move onclick target to avoid updating several tests
- The behavior works as is but we need to upgrade several tests to change click target. Instead of that moved onClick target to parent
=> fix: [PIE-4356]: move onclick target to avoid updating several tests

packages/uicore/src/components/Page/PageError.css, packages/uicore/src/components/Page/PageError.tsx, packages/uicore/src/components/Page/__tests__/__snapshots__/PageError.test.tsx.snap
Adds a dummy class to PageError so that it can be overridden in NGUI
=> fix: [PL-24388]: add PageError class

packages/uicore/src/frameworks/Tooltip/Tooltip.tsx
=> fix: [CDS-40891]: restricted toggling when clicking the info icon

packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx, packages/uicore/src/components/ConfirmDialog/useConfirmationDialog.tsx
=> fix: [CDS-40874]: added support for children in useConfirmationDialog

packages/uicore/package.json, packages/uicore/src/components/GroupedThumbnailSelect/GroupedThumbnailSelect.tsx
=> fix: [PIE-4750]: grouped thumbnail select update groups on change

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/MultiSelect/MultiSelect.css, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
Summary:
add usePortal and popoverClassName to MultiSelect component to support dropdown opening in portal div
Screenshots:
=> chore: [CDS-41745]: add usePortal and popoverClassName to MultiSelect component

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.test.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
Updates `ModalDialog` component to fix these issues:
- When the child element has height set to 100% it is causing the modal body to get a vertical scroll bar. This is because the lines (:before, :after) that are used as scroll indicators have 1px heights. So the content can only have `100%-2px` height if we want to prevent scroll bar.
- The [design](https://www.figma.com/file/bYQtU9kWVuVEsLksbVgGM4/hex2o?node-id=18966%3A154501) uses box shadows instead of lines for scroll indicators.
Changes:
- Used intersection observer instead of scroll events for displaying scroll indicators, as the observer is better for performance and also works for dynamic content. 
- Box shadows are used instead of lines.
**Before:**
short content with 100% height
long content
**After:**
short content with 100% …
=> fix: [PL-27934]: Use intersection observer for scroll shadows, fix vertical scroll

packages/uicore/package.json, packages/uicore/src/utils/errorUtils.ts
=> feat: handle abort errors in firefox

packages/uicore/package.json, packages/uicore/src/components/Select/Select.css, packages/uicore/src/components/Select/Select.tsx, packages/uicore/src/components/Select/__snapshots__/Select.test.tsx.snap
https://user-images.githubusercontent.com/106532291/191431947-2148c933-eaa5-497f-829f-c263b174c013.mov
- Added additional loading prop to the Select component to show loading results instead of no results found in case of search query
- changed text from Nothing Found to No Match Found
- the scoping for the css of No Match Found was changed as it wasn't getting applied
- Attached video for reference ^^
=> fix: [CDS-42827]: added optional prop for loading state in Select Field

packages/uicore/src/components/Select/Select.tsx
- In the select dropdown the add new icon only shows up when we don't have an element with exact case sensitive match
https://user-images.githubusercontent.com/106532291/195305966-5954c895-e176-47df-9e97-8414459fddd6.mov
=> fix: [CDS-44566]: show add new item only when exact match doesn't exist (Case Sensitive)

packages/uicore/src/components/MultiSelectDropDown/MultiSelectDropDown.css, packages/uicore/src/components/MultiSelectDropDown/MultiSelectDropDown.tsx
1. In Multi Select Dropdown component if the dropdown items are empty the entire component was disabled
2. Instead of this added no results found dropdown
3. Count was showing as blue even if was disabled.
https://user-images.githubusercontent.com/106532291/195592826-720d2deb-1914-4fa2-9d9c-64f999dd75b3.mov
=> fix: [CDS-44566]: no results and disabled issue for multiSelectDropdown

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
- Fixes an error related to `FileInput` placeholder caused by mapping the value when it's not an array.
- Adds a new prop to prevent formik value update on change.
=> fix: fix error in FileInput when multiple is falsy

packages/uicore/package.json, packages/uicore/src/components/Button/Button.tsx, packages/uicore/src/components/CollapsableSelect/__snapshots__/CollapsableSelect.test.tsx.snap, packages/uicore/src/components/FieldArray/__snapshots__/FieldArray.test.tsx.snap, packages/uicore/src/components/FormikForm/__tests__/__snapshots__/FormikForm.test.tsx.snap, packages/uicore/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/uicore/src/components/Page/__tests__/__snapshots__/PageSubHeader.test.tsx.snap, packages/uicore/src/components/Pagination/__test__/__snapshots__/Pagination.test.tsx.snap, packages/uicore/src/components/StepWizard/__snapshots__/StepWizard.test.tsx.snap
=> feat: [PIE-5932]: Add explicit aria-label, when text is present (in case of icon, rightIcon, we want voiceover to read only text)

packages/uicore/package.json, packages/uicore/src/components/Button/Button.css, packages/uicore/src/components/Button/Button.stories.tsx
=> feat: [CDS-45863]: button with secondary intent, Secondary + intent was not available earlier

packages/uicore/package.json, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx, packages/uicore/src/components/ConfirmDialog/useConfirmationDialog.tsx
=> feat: [PIE-6237]: className support for useConfirmationDialog

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
Summary:
The form values for the KVTagInput field would not show up on the UI if the name path needs to be resolved. For ex: 'path1.path2.0.path3'. Added support to handle this
Now:
https://user-images.githubusercontent.com/96711906/202395898-afb22938-6b8f-44eb-a552-e0d8b3df3f83.mov
Before: 
https://user-images.githubusercontent.com/96711906/202399166-96364485-7d9c-46e2-9a63-c15e7ed44ac8.mov
=> fix: [PIE-5881]: resolve path of tag input field value

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
Updates width prop type to accept all CSS width values.
=> fix: update width prop type

packages/uicore/package.json, packages/uicore/src/components/TableV2/TableV2.tsx
=> fix: [SRM-12658]: externalize autoResetSortBy & autoResetPage in TableV2

packages/uicore/src/components/StringSubstitute/StringSubstitute.tsx, packages/uicore/src/index.ts
This component substitutes an i18n string with values as React components.
**Example**
```tsx
// strings.en.yaml
metaLine: '{user} wants to merge {number} {number|1:commit,commits} into {target} from {source}'
const vars = {
user: <strong>{createdBy}</strong>,
number: 1, 
target: <GitRefLink text={targetBranch} />,
source: <GitRefLink text={sourceBranch} />
}
<StringSubstitute str={getString('pr.metaLine')} vars={vars} />
```
**Output:**
=> feat: Add StringSubstitute component

packages/uicore/package.json, packages/uicore/src/components/FormikForm/__tests__/FormikForm.test.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
This updates the `ExpressionAndRuntimeType` component to prevent clearing the value when the type is switched from fixed to expression. The value is cleared in all other cases.
https://user-images.githubusercontent.com/52284933/207789194-0f093257-c4c8-4927-9ff3-5aa7183f761f.mov
=> feat: [PIE-6791]: retain value when switching from fixed to expression type

packages/uicore/package.json, packages/uicore/src/components/Thumbnail/Thumbnail.tsx
=> fix: [CDS-47282]: fixed render view of label as ReactElement for ThumbnailSelect component

packages/uicore/src/components/Avatar/Avatar.stories.tsx, packages/uicore/src/components/Avatar/Avatar.test.tsx, packages/uicore/src/components/Avatar/Avatar.tsx, packages/uicore/src/components/Avatar/utils.ts, packages/uicore/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
JIRA: https://harness.atlassian.net/browse/PL-30311
ES6+ treats `null` and `undefined` differently in case you provide a default value to a function. 
The default value for `name` (empty string) was not being picked up in case name was provided as null. Fixed it by adding null checks and `defaultTo`.
**No Name, email or src**
**How it looks in Avatar Group**
Before
After (different sizes)
=> feat: [PL-30311]: Avatar component—added null checks on both name & email 

packages/uicore/package.json, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx
Fix word Wrap issue in Confirmation Dialog using `<Text/>` component and lineClamp
BEFORE:
AFTER:
=> feat: [PL-29962]: fix word-wrap issue 

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.stories.tsx, packages/uicore/src/components/DropDown/DropDown.tsx
- dropdown takes a promise function to get the list of items but that's called immediately on mount and disable the field if no items are found
- `getLazyItems` provides an option to defer the call until the dropdown is opened. This will be called on the dropdown open and this function is responsible for fetch and update of the items
- This goes well with refetch + data combination of queries and even when multiple parents need the same data Ex: (Dropdown + some other component) need the same data from query
=> feat: PIE-7367: extend UICore dropdown to allow for lazy loading of items

packages/uicore/package.json, packages/uicore/src/components/ExpandingSearchInput/ExpandingSearchInput.tsx
`ExpandingSearchInput` will now autofocus by default unless overriden to be false.
=> feat: [PL-30656]: autofocus search input across the board

packages/uicore/src/components/Avatar/Avatar.css
Issue - This issue is happening only in chrome. Default stacking behaviour of position static elements is changed in the latest version. 
Before
After
=> feat: [PL-30704]: Avatar overlap issue fix

packages/uicore/package.json, packages/uicore/src/components/SplitButton/SplitButton.tsx
=> fix: tooltip should come only on the main btn of split btn

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.tsx
fixes https://harness.atlassian.net/browse/PIE-7765
reverts https://github.com/harness/uicore/pull/841
The way the dropdown component API evolved, not able to fix it without removing this, else we need to update places where it's used
=> fix: [PIE-7765]: dropdown race conditions in search due to debounce and parent state

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.tsx, packages/uicore/src/components/Pagination/Pagination.tsx
Updated Dropdown component to enable `popoverProps` prop.
Added new prop `pageSizeDropdownProps` to Pagination to customize the page size dropdown.
=> feat: [PL-30747]: update Dropdown, Pagination to take popoverProps

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.tsx
Issue - Selected item gets reset when the list is refreshed based on the query. This happens when the selected item is not part of the dropdown list (after list gets reset on different query).
=> feat: [PL-30529]: Showing selected item in case the item is missing in the dropdown list

packages/icons/package.json, packages/uicore/src/components/SplitButton/SplitButton.stories.tsx, packages/uicore/src/components/SplitButton/SplitButton.tsx
=> feat: Add popoverProps into SplitButton for extra customization

packages/uicore/package.json, packages/uicore/src/components/TabNavigation/TabNavigation.tsx
```Added exact and strict optional props for navlinks```
=> feat: [CDS-49922]: add exact and strict optional props for nav links

packages/uicore/package.json, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx
- Fixes Run/Rerun Pipeline - When setting the runtime field to Expression and hitting Enter on the auto-complete option, pipeline execution will kick off immediately
- Stopped event propagation to prevent event bubbling
=> fix: [CDS-53063]: expression selection upon entering should not submit the form

jest/setup-file.js, packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
Updates ModalDialog to fix escape key close, outside click close, and to render scroll shadows before transition.
=> fix: [PL-31466]: escape key close, outside click close - ModalDialog

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
=> chore: [CDS-53833]: override prop to reset value on fixed to expression type change

packages/uicore/package.json, packages/uicore/src/components/InputWithIdentifier/InputWithIdentifier.tsx
JIRA: https://harness.atlassian.net/browse/PL-31769
Added a callback onIdentifierChangeCallback in InputWithIdentifier.
It gets triggered when identifier changes, either directly or due to changes in name field
----
=> feat: [PL-31769]: added callback onIdentifierChangeCallback in InputWithIdentifier

packages/uicore/package.json, packages/uicore/src/frameworks/Tooltip/Tooltip.css
JIRA: https://harness.atlassian.net/browse/PL-32462
Increased tooltip icon margin for bigger hoverable area
Screenshots:
**BEFORE: Only left margin (& icon itself) for hover**
https://user-images.githubusercontent.com/96057095/230608282-85c4ec34-317f-447a-ad81-b3387c21c8e7.mov
**AFTER: Left, bottom & Right Margin (& icon itself) for hover. Not using top-margin as it misaligns the icon with respect to the text.**
https://user-images.githubusercontent.com/96057095/230608342-a60f44cc-a630-4ff5-8925-2e644e2af2d2.mov …
=> fix: [PL-32462]: increased tooltip icon margin for bigger hoverable area

packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
=> feat: [STO-5670]: Add placeholder prop for text input modes of MultiTypeInput

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
Added `isIdentifier` optional boolean prop to `FormInput.Text` so that the field can be used as Identifier field and behave same as Id field in `InputWithIdentifier`
=> fix: [CDS-58678]: Added support for FormInput.Text to be used as Identifier field

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.stories.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.test.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
**Changes to support the behaviour :** 
https://user-images.githubusercontent.com/63278928/232852497-6a30e74f-8449-4e37-b255-53407c976697.mov
Behaviour with current support where only content can be wrapped in Overlay by consumer ( not header and footer)
https://user-images.githubusercontent.com/63278928/232853412-51596975-5516-4a3d-aa23-bc7b5863cdae.mov
=> feat: [PIE-9697]: Adding Overlay support in ModalDialog

packages/uicore/package.json, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx, packages/uicore/src/index.ts
- Text area component for expression inputs 
https://user-images.githubusercontent.com/106532291/232557328-4edb5cd6-ca08-419a-8f36-e6384c93f5ef.mov
=> feat: [PIE-9634]: Text area editable component 

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.stories.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.test.tsx, packages/uicore/src/components/ModalDialog/ModalDialog.tsx, packages/uicore/src/components/OverlaySpinner/OverlaySpinner.tsx
[Earlier changes](https://github.com/harness/uicore/pull/1031) were breaking modal with long contents.
- Now without overlay, there is no change in DOM and behaviour.
- With overlay, we have handled the long content behind overlay by CSS.
**After fix:** 
https://user-images.githubusercontent.com/63278928/233017003-6fa0ef31-809b-4a7d-9eb5-79a057d6151b.mov
=> fix: [PIE-9697]: Fix for modal dialog with Overlay

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
Removing useMemo introduced in [previous PR](https://github.com/harness/uicore/pull/1032/files#diff-a1c84da032777acb9627a2bbf2bf4efc9b65d29361cde2ba747f5ced9e432fa9L146) due to side effects
=> fix: [PIE-9318]: Removing memo in modalContent introduced in last PR

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
ModalDialog no longer relies on blueprint dialog's lifecycle callbacks for creating and removing scroll shadows. This fixes an issue with incorrect scroll shadows in some usages.
=> fix: init scroll shadows without depending on blueprint dialog lifecycle

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
[Earlier change](https://github.com/harness/uicore/pull/1041) were leading to jest failure with below error : 
```
TypeError: t.disconnect is not a function
at node_modules/@harness/uicore/dist/webpack:/@harness/uicore/src/components/ModalDialog/ModalDialog.css:2:391
at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
```
=> fix: [fix_modaldialog]: Added function check before invoking

packages/uicore/package.json, packages/uicore/src/components/SplitButton/SplitButton.tsx
=> fix: [CDS-68201]: add portal support for SplitButton

packages/uicore/package.json, packages/uicore/src/hooks/useToaster/useToaster.css, packages/uicore/src/hooks/useToaster/useToaster.stories.tsx
- Makes the warning toast background orange instead of yellow
- Adds stories for toaster hook to improve documentation
Old warning:
New Toasts:
=> feat: [PL-32524]: improve readability of warning toasts

packages/uicore/package.json, packages/uicore/src/components/Accordion/Accordion.tsx, packages/uicore/src/components/AccordionTabs/AccordionTabs.stories.tsx, packages/uicore/src/components/AccordionTabs/AccordionTabs.test.tsx, packages/uicore/src/components/AccordionTabs/AccordionTabs.tsx, packages/uicore/src/index.ts
- Added controlledActiveId support for Accordion which allows accordion panels to be driven by controlledActiveId which can be changed via onChange
- Added AccordionTab component which renders horizontal Tabs with vertical Accordion.Panel corresponding to each Tab
https://github.com/harness/uicore/assets/100121280/803300f3-af64-409f-8d31-0bdfdc5cb530
=> feat: add AccordionTab component + controlled accordion support in Accordion

packages/design-system/package.json, packages/design-system/src/styled-props/background.css
Reverting few changes from https://github.com/harness/uicore/pull/742 to avoid unintentional snapshot updates in https://github.com/harness/harness-core-ui/pull/16175 due to version bump `1.0.0` -> `1.5.1`
=> fix: [CI-8191]: Revert background css to fix version bump issue

packages/uicore/package.json, packages/uicore/src/components/StepWizard/StepWizard.tsx
Added support for user defined watermark icon in StepWizard. Since Litmus 3.0 beta utilises ui-core library, we need a prop to pass custom icons for watermark. 
It has been added as an optional prop that defaults to `harness-with-color` icon.
=> feat: [CHAOS-1910]: Add support for user defined watermark icon in StepWizard

packages/uicore/package.json, packages/uicore/src/components/Button/Button.tsx
ReactQuery refetch returns Promise<DataType> but not Promise<void>
```
const {isLoading, refetch} = Query(...)
<Button onClick={() => refetch()} loading={isLoading} />
=> feat: SSCA-269 update button click return type to work with RQ refetch

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
- `getMultiTypeFromValue` return expression type even if the allowed types doesn't contain expression type
https://github.com/harness/uicore/assets/106532291/79039915-8cdc-4070-9c78-41e4c7a8a63a
=> fix: [CDS-73038]: getMultiType return expression type even if the allowed types doesn't contain expression

packages/uicore/package.json, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.css, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx
**Issue** - lineClamp property on contentText in ConfirmationDialog was causing text breaking issue across all the confirmation dialog's through out the Harness app. There were multiple issues raised recently for different dialog's. 
**fix** - Removed the line-clamp and added break-word property, line-clamp should be added by child component instead of the common component. ConfirmationDialog shouldn't restrict the content text to be not more than 5 lines. 
Also, the type of contentText is ReactNode, wrapping it in `<Text>` doesn't make sense. 
Issues raised recently - 
https://harness.atlassian.net/browse/PL-40071
https://harness.atlassian.net/browse/PL-40070
- Type Check: …
=> feat: [PL-40071]: Removing lineclamp from contentText in confirmation dialog

packages/uicore/package.json, packages/uicore/src/components/Select/BiLevelSelect.tsx, packages/uicore/src/components/Select/Select.css, packages/uicore/src/components/Select/Select.stories.tsx, packages/uicore/src/components/Select/Select.tsx
- Add right icon to the select option dropdown
https://github.com/harness/uicore/assets/106532291/f7c9a676-31c9-4ce7-8eab-2fa6c8c83a1d
=> feat: [CDS-73647]: add right Icon support for select label

packages/uicore/package.json, packages/uicore/src/components/ExpandingSearchInput/ExpandingSearchInput.tsx
=> fix: [CDS-75164]: trimmed searchterms for expandingSearchInputs

packages/uicore/package.json, packages/uicore/src/components/ExpressionDropdown/ExpressionDropdown.tsx, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/frameworks/Tooltip/Tooltip.tsx
Jira: https://harness.atlassian.net/browse/CDS-75452
Error: **ResizeObserver loop completed with undelivered notifications.**
**Summary:**
Since many stack trace point to expression component and few instances of stack-trace referencing to https://widget.saberfeedback.com/v2/widget.js:1:63953 createSaberObject/window.Saber</event_log</window.onerror. 
The underlying issue can be due to unnecessary re-renders or some event bubbling to blueprintJS components triggering ResizeObserver API being consumed by Popovers, Menu etc. components from blueprintJS.
There were multiple warning related to `[Blueprint] <Popover> onInteraction is ignored when uncontrolled.` which can be the potential root cause for the error .
**Fix:**
- Avoid unnecessary re-renders for Expression Dropdown component
- …
=> fix: [CDS-75452]: suppress onInteraction warning + optimise ExpressionDropdown ( Resize Observer limit reacher Error )

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
=> fix: [CDS-74650]: allowed onChange to override from the caller via props for KVTagInput

packages/uicore/package.json, packages/uicore/src/components/FormikForm/__tests__/FormikForm.test.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
**Summary:**
Without this fix, whichever consumer does not send defaultValueToReset as empty string to MultiTypeInput component will cause page crash, if tried to access value out of selected item without adding null check before that.
So, handled it generically in this common component add set empty string as default value for the prop.
Jira: https://harness.atlassian.net/browse/CDS-76216
=> fix: [CDS-76216]: set default value of defaultValueToReset as empty string in ExpressionAndRuntimeType component

packages/uicore/package.json, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
https://github.com/harness/uicore/assets/106532291/9fb0c2f2-610c-4a3d-ba02-27bb3b61c428
=> fix: [CDS-76354]: closing tag being added at wrong cursor position

packages/uicore/package.json, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
- Handle case when adding `>` without the expression being present the text was being added as HTML Tag , sanitized the HTML in this case
- Maintained the caret position correctly for this edge case
- added extra range condition for complete (non text) nodes
https://github.com/harness/uicore/assets/106532291/3b268d10-aecc-44df-8f51-b25db0a6aeda
=> fix: handle the sanitize for text elements

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
- Escape new line characters in multi text input field
https://github.com/harness/uicore/assets/106532291/8ada3e3b-99d4-4b6b-b749-c56f45740166
=> fix: [CDS-76660]: escape newline characters for multi text input fields

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/FormikForm/__tests__/utils.test.tsx, packages/uicore/src/components/FormikForm/utils.tsx
- handled number cases for escape new line function
=> fix: [CDS-76660]: handled number cases for escape new line function

packages/uicore/package.json, packages/uicore/src/components/Select/Select.tsx
Editing support for custom label for new item label in Select. 
Before label was fixed as : **+ query** , Now consumer can use any label, ex:  **> Select branch main-patch**
Changes were done after the feedback in earlier flow as discussed in [CDS-74577](https://harness.atlassian.net/browse/CDS-74577)
**Before fix**
**After fix :** 
Renderer used to test in NGUI :
```
const renderCustomSelectBranch = (
query: string,
clickHandler?: React.MouseEventHandler<Element>
): React.ReactElement => (
<Button
intent="primary"
minimal
text={`Select branch ${query}`}
icon="chevron-right"
className={css.createNewItemButton}
onClick={clickHandler}
/>
)
```
- Type Check: `retrigger …
=> feat: [CDS-74577]: Adding support for custom newItemRenderer label

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
**Issue:** On changing multiselecttypeinput from expression or runtime to fixed, page crashed
**Fix:** This issue was because defaultvalue was getting reset to empty string. So updated it to empty array which is expected default value.
Before fix:
https://github.com/harness/uicore/assets/98508399/2a36d95f-4ca9-4653-bbe1-3bc1349703bc
After fix:
https://github.com/harness/uicore/assets/98508399/89d2fd9a-983c-4343-8615-3baa8b258f6c
=> fix: [CDS-77988]: For multiselecttypeinput set defaultValueToReset as []

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
Summary:- 
- The placeholder was being passed as `inputProps` under `tagInputProps` , but the component only considered the placeholder being passed at root level.
https://github.com/harness/uicore/assets/106532291/2bf73383-3865-48ee-bbf8-7acde7442453
=> fix: [CDS-78728]: FormInput.MultiSelect showing different placeholders on select and empty state

packages/icons/package.json
Increased version in prev PR but a parallel PR merged in between with same version, so the new icons are not available in that
=> feat: [SSCA-642] ssca nav icons increment version

packages/uicore/package.json, packages/uicore/src/components/Breadcrumbs/Breadcrumbs.css, packages/uicore/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/uicore/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
=> fix: breadcrumbs snapshot changes revert

packages/uicore/package.json, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
- `plaintext-only` is not supported for `firefox` .
-  MDN-Docs :-  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
- https://bugzilla.mozilla.org/show_bug.cgi?id=1291467 feature request to add support for `plaintext-only` in firefox
https://github.com/harness/uicore/assets/106532291/ab84256b-3f5f-4c11-93b3-d7e28a95a0ef
=> fix: [CDS-79162]: edit expressions in firefox

packages/uicore/package.json, packages/uicore/src/components/GridListToggle/GridListToggle.css, packages/uicore/src/components/GridListToggle/GridListToggle.tsx, packages/uicore/src/components/GridListToggle/__snapshots__/GridListToggle.test.tsx.snap
This fixes failing snapshot tests in ng-ui by removing `gridButton` class which was added in https://github.com/harness/uicore/pull/1171 to the `LIST` view button component
=> fix: [CDS-80395]: fix failing TCs

packages/uicore/package.json, packages/uicore/src/components/TagInput/TagInput.tsx
TagInput component uses a generic type for items, but a few functions inside it expect items to have certain keys (like value, label, etc.) if they are objects, making it impossible to use this for any item type. This PR removes these functions.
Verified that removing these functions doesn't break anything.
=> fix: [CDS-78994]: Make TagInput usable for any item type

packages/uicore/package.json, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css
- fix variable not respecting the width in variables window as the `whitespace:pre` doesn't wrap the text where as `pre-wrap` solves our use case
Tested Scenarios :- 
- Edit expressions in `chrome` with long expressions
- Edit expressions in `firefox` with long expressions
- Edit long expressions in `harness-core-ui`
https://github.com/harness/uicore/assets/106532291/8347df09-1ebd-4dc3-8c8c-f66ad107daa2
=> fix: [CDS-81644]: variable not respecting the width in variables window

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
This PR fixes an issue whereby using the `useValue` prop with no initial value set on the `FormMultiSelectTypeInput` would result in an error being thrown.
=> fix: [FFM-9721]: Ensure value defaults to empty array

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx
Update `FormInput.TextArea` and `FormInput.MultiTextInput` to pass an empty string to the underlying input element if `value` is null/undefined to fix React warnings related to controlled components.
Example warning:
=> fix: [CDS-80690]: Use empty string if value is nil for controlled inputs

packages/uicore/package.json, packages/uicore/src/utils/errorUtils.ts
- Adds **`Failed to fetch: signal is aborted without reason`** to **IGNORED_ERRORS**
This error was recently introduced in Apollo Client 3.7.4 
=> fix: [CDS-80179]: add abort error in IGNORES_ERRORS

packages/uicore/src/components/Stepper/Stepper.stories.tsx, packages/uicore/src/components/Stepper/Stepper.tsx, packages/uicore/src/components/Stepper/Stepper.types.ts, packages/uicore/src/components/Stepper/__tests__/Stepper.mock.tsx, packages/uicore/src/components/Stepper/__tests__/Stepper.test.tsx, packages/uicore/src/components/Stepper/components/Step/Step.constants.ts, packages/uicore/src/components/Stepper/components/Step/Step.module.css, packages/uicore/src/components/Stepper/components/Step/Step.module.scss.d.ts, packages/uicore/src/components/Stepper/components/Step/Step.tsx, packages/uicore/src/components/Stepper/components/Step/Step.types.ts, packages/uicore/src/components/Stepper/components/Step/Step.utils.ts, packages/uicore/src/components/Stepper/components/Step/components/StepNavButtons/StepNavButtons.tsx, packages/uicore/src/components/Stepper/components/Step/components/StepNavButtons/StepNavButtons.types.ts, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.constants.ts, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.module.css, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.module.scss.d.ts, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.tsx, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.types.ts, packages/uicore/src/components/Stepper/components/Step/components/StepTitle/StepTitle.utils.ts
=> feat: [SRM-16021]: Added Stepper component

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.css, packages/uicore/src/components/ModalDialog/ModalDialog.tsx
**Issue:** modalContent unmount when showOverlay is true. This led to loss of data for modalContent
**Fix:** Do not unmount modalContent on change of showOverlay
=> fix: [CDS-81020]: Fix ModalDialog OverlaySinner

packages/uicore/src/components/DropDown/DropDown.tsx
Issue - `onQueryChange` doesnt return any response when utlised in harness-core-ui when items passed is an array.
=> fix: [PL-42962]: add onQueryChange in Dropdown component

packages/uicore/package.json, packages/uicore/src/components/MultiSelectDropDown/MultiSelectDropDown.tsx, packages/uicore/src/components/MultiSelectDropDown/__tests__/MultiSelectDropdown.test.tsx
This PR adds a new optional prop into the ExpandingSearchInput component within the MultiSelectDropdown component. This should allow the ExpandingSearchInput to make searches via api requests 
=> feat: [FFM-10188]: multiselectdropdown prop

packages/uicore/package.json, packages/uicore/src/components/Accordion/Accordion.tsx
Added className in panel props, it's required to make changes on module panel in the ModuleAccordion component of new nav. 
=> fix: [CDS-88240]: added classname prop in accordion panel

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
Jira: https://harness.atlassian.net/browse/PL-43925
Prevent default reset-to-top for MultiSelect
BEFORE:
https://github.com/harness/harness-core-ui/assets/96057095/cd7e6dbe-f873-49ae-a485-93d052e29c66
AFTER:
https://github.com/harness/harness-core-ui/assets/96057095/3fa55cd3-f55d-45f4-8397-92961c53e2cb
=> fix: [PL-43925]: Prevent default reset-to-top for MultiSelect

packages/uicore/package.json, packages/uicore/src/components/TagsPopover/TagsPopover.tsx
=> fix: [chore/CDS-85482]: add support for title and className in the tagPopover component

packages/uicore/package.json, packages/uicore/src/components/Accordion/Accordion.tsx
Accordion component expects child to be Accordion.Panel component always. We can't render any other component as child. 
This causes the issue when rendering the Accordion.Panel component conditionally. Adding shouldRender property to show/hide the Accordion.Panel component
=> feat: [CDS-88611]: Added shouldRender property in accordion panel

packages/uicore/package.json, packages/uicore/src/hooks/useToaster/useToaster.css
Added harness primary color for toast variant primary, the default blueprint color was being used earlier
=> feat: [CDS-89316]: Using harness primary color for toast variant primary

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.stories.tsx, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
**Issue:** 
Scroll was resetting to top after every selection . 
**Fix:** 
Fixed the scroll reset using resetOnQuery : false . 
Have kept the changes backward compatible and right now consumer has to use the prop { avoidResetOnSelect: true} . 
Once these changes will be tested and verified  for `MultiSelectVariableAllowedValues` component we will ask PM whether to make this itself a default behaviour or not, for all multi-select.
**Use case tested :** 
- Selection change : working
- Search by query change : working
Changes is tested with NGUI using yalc for which screen recordings are added.
**Current behaviour with scroll reset** 
https://github.com/harness/uicore/assets/63278928/76b9971c-089e-4c63-8648-0278c0f1d120
**After fix:** …
=> fix: [CDS-93893]: Fixing scroll reset for multiSelect after selection

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
Follow up PR of https://github.com/harness/uicore/pull/1261 
We have to reset the query for allowCreatingNewItems. 
=> fix: [CDS-93893]: Ignoring the reset if allowCreatingNewItems is used

packages/uicore/package.json, packages/uicore/src/components/Dialog/Dialog.test.tsx, packages/uicore/src/components/Dialog/Dialog.tsx
This fix prevents warning:
```[Blueprint] <Dialog> isCloseButtonShown prop is ignored if title is omitted. ```
=> fix: [CDS-93392]: prevent blueprintjs warning

packages/uicore/package.json, packages/uicore/src/components/SplitButton/SplitButton.css
=> fix: Fix wrong CSS targeting in SplitButton

packages/uicore/package.json, packages/uicore/src/hooks/useToaster/useToaster.tsx
- Hides toast banner for empty message
=> fix: [PIPE-18595]: hide toast if message is empty string

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/components/MultiTypeInput/TypeSelectorButton.tsx, packages/uicore/src/hooks/useToaster/useToaster.tsx
- During profiler investigation, that the button and SVG component are re-rendering due to 2 reasons
1. The parent component was re-rendered 
2. In most cases it was due to unrelated props changes in value, expressions, etc.
- For a pipeline with many inputs, number of re-renders across inputs in the following interaction journey
-- Open RPF
-- Input test in first input
-- Change type from Fixed to Expression
-- Switch to YAML view and Visual View again
**Reduced ~10% from 6345 to 5712** 
| Before | After |
| -- | -- |
|![image](https://github.com/harness/uicore/assets/100121280/c73de2dd-e17f-4a36-9a15-0aa560f716e9) | ![image](https://github.com/harness/uicore/assets/100121280/4ec40978-36e1-49ff-867a-c1e4f21757f6) |
- Jest: …
=> chore: [CDS-95922]: Optimized button rendering logic with useCallback

packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
**Issue:**
TextAreaEditable component disable property is not working, since disable property is not used to set the content-editable attr
**Fix:**
- set  content-editable attribute to disabled prop
- handle keydown on callback should be undefined when disabled is true
Before: 
https://github.com/harness/uicore/assets/164848360/355285c2-67cb-42e3-b5e2-ac9930d19d44
After:
https://github.com/harness/uicore/assets/164848360/45148192-6a16-42df-9b4b-a826a698762f
=> fix: [CDS-96282]: Disable TextAreaEditable

packages/uicore/package.json
Fixed textAreaEditable component disable feature in my previous the https://github.com/harness/uicore/pull/1303, Created a new PR for version bump
=> chore: Version bump for textAreaEditable component disable fix

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
This will be used to prevent popover close. 
Use case described in: https://harness.atlassian.net/jira/software/c/projects/PIPE/issues/PIPE-18571?filter=18890
Tech details: https://blueprintjs.com/docs/#core/components/popover.closing-on-click
=> feat: [PIPE-18571]: expose popover's captureDismiss for KVTagInput component

packages/uicore/package.json, packages/uicore/src/components/GroupedThumbnailSelect/GroupedThumbnailSelect.tsx
`GroupedThumbnailSelectProps` extends `ThumbnailSelectProps` which already has `expandAllByDefault` prop, but we were not consuming it.
=> feat: [IDP-2801]: expandAllByDefault prop added to GroupThumbnailSelect

packages/uicore/package.json, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
Changes and their impact:
1. **Moving JSX of Popover Second Child to JSX Block:** 
Earlier the JSX for the dropdown was being created and rendered every time the renderer function was called, moving this into a separate JSX block (<ExpressionDropdown />) will now render when needed ( popover opened) to avoid creation and rendering of the dropdown when the popover is closed
2.  **Using useMemo for filteredItems:**
For large `items` array, the react state is recalculated every time the queryValue or items prop is changed, moving them to useMemo ensures that the filtering operation is only performed when necessary.
- ESLint: `retrigger …
=> chore: [PIPE-18794]: optimise the ExpressionInput component

packages/uicore/package.json, packages/uicore/src/components/ListHeader/ListHeader.css, packages/uicore/src/components/ListHeader/ListHeader.stories.tsx, packages/uicore/src/components/ListHeader/ListHeader.tsx, packages/uicore/src/components/ListHeader/ListHeaderStory.css
This PR adds the support to pass any custom content to ListHeader to be shown with the Sort Filter.
Also added story for ListHeader with and without content.
**- ListHeader with content:**
<br/>
**- ListHeader without content (Existing behaviour):**
<br/>
**- ListHeader in harness core UI with  content:**
<br/>
**- ListHeader in harness core UI without content (Existing behaviour):**
=> feat: [PIPE-18812}]: Add support for passing content to ListHeader

packages/uicore/package.json, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx, packages/uicore/src/components/ConfirmDialog/useConfirmationDialog.tsx
JIRA:
https://harness.atlassian.net/browse/CDS-97305
Before:
After:
| A    | B |
| -------- | ------- |
| Long Text  ![Screenshot 2024-05-27 at 3 42 22 PM](https://github.com/harness/uicore/assets/164848360/d3eab5e7-c7a5-4c81-839e-59860a458ff0)   |
| Normal Text ![Screenshot 2024-05-27 at 3 59 16 PM](https://github.com/harness/uicore/assets/164848360/c3201436-8e68-4609-bace-3b46c119498c) | Mixed text ![Screenshot 2024-05-27 at 3 43 18 PM](https://github.com/harness/uicore/assets/164848360/c59bb261-57bd-47e9-8d65-6c6e3380a38a)
- Title Check: …
=> fix: [CDS-97305]: fixed confirmation dialog header long text

packages/uicore/package.json, packages/uicore/src/components/ListHeader/ListHeader.stories.tsx, packages/uicore/src/components/ListHeader/ListHeader.tsx, packages/uicore/src/components/ListHeader/ListHeaderStory.css
This PR adds the support to pass preDropdownContent &  postDropdownContent to ListHeader to be shown with the Sort Filter.
Enhancement made to changes in https://github.com/harness/uicore/pull/1318
- **With preDropdownContent & postDropdownContent**
- **With postDropdownContent**
- **With preDropdownContent**
- **No preDropdownContent & postDropdownContent**
- **With postDropdownContent in Hanerss Core UI**
=> feat: [PIPE-18812]: Add support for preDropdownContent & postDropdownContent for ListHeader

packages/uicore/package.json, packages/uicore/src/components/Tabs/Tabs.tsx
JIRA: https://harness.atlassian.net/browse/PL-51672
**Problem:** Tabs component does not honour "className" prop. 
**Solution:** Passed className from props to `<BpTabs ... />`
BEFORE:
AFTER:
Random className: `hohoho` is honoured
=> feat: [PL-51672]: Passed className from props to BpTabs

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
As a follow up to PR https://github.com/harness/uicore/pull/1333, this change is to ensure backward compatibility, since an existing `onFocus` prop passed, if any, should be honored and not swallowed instead.
=> fix: [PIPE-20089]: Bug fix to honor "onFocus" from props

packages/uicore/package.json, packages/uicore/src/components/TableV3/TableV3.css, packages/uicore/src/components/TableV3/TableV3.stories.tsx, packages/uicore/src/components/TableV3/TableV3.tsx, packages/uicore/src/index.ts, yarn.lock
Changes - 
* Removed the ExecutionList dependency from the TableV3 component to make it more generic.
* Added support for column pinning and scrolling.
* Added TableV3 to Storybook.
The design is not finalized yet; we are working with the design team to provide the proper colors and font sizes. This is just the first commit and contains only the structure of the table. There will be more commits once the requirements are finalized.
Why TableV3 is required when we have TableV2:
- We recently received requirements from the design team for multiple tables that need features such as scrolling, column pinning, and showing/hiding columns, which are not supported in TableV2.
- we are now using latest version of react-table
https://github.com/user-attachments/assets/8a462a67-2671-4cdb-9a2c-383074a …
=> feat: [DBOPS-347]: Table v3 component initial commit. 

packages/uicore/package.json, packages/uicore/src/components/CollapsableSelect/CollapsableSelect.test.tsx, packages/uicore/src/components/DropDown/DropDown.stories.tsx, packages/uicore/src/components/Page/__tests__/PageError.test.tsx, packages/uicore/src/components/SelectWithSubmenu/SelectWithSubmenuV2.tsx, packages/uicore/src/frameworks/Tooltip/TooltipContext.tsx
While using `@harnessio/uicore@4.1.2` in an open source project, we noticed this error popping up. 
Upon inspection if uicore, we noticed that some types were imported from the `index` file which was causing the same.
After fixing this in uicore repo and testing with yalc we can confirm that this fixes our issues. 
=> fix: [IRO-283]: fixed issues with cyclic dependencies

packages/uicore/package.json, packages/uicore/src/components/ExpandingSearchInput/ExpandingSearchInput.tsx, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.tsx, packages/uicore/src/components/Filters/components/FilterTextInput/FilterTextInput.tsx, packages/uicore/src/components/Filters/components/FiltersMultiSelectDropDown/FiltersMultiSelectDropDown.tsx
- remove onRemove when icon is dropdown
- add setValue prop to expanding search input
=> fix: [CDS-100078]: Filters V2 fixes 

packages/uicore/package.json, packages/uicore/src/components/Accordion/Accordion.css, packages/uicore/src/components/Accordion/Accordion.stories.tsx, packages/uicore/src/components/Accordion/Accordion.tsx
Adding support for accordion icon positioning
https://github.com/user-attachments/assets/e4153630-d38a-4908-bfbd-e3b653b798ee
=> feat: [PIPE-21132]: added support for chevron positioning in accordion

packages/uicore/package.json, packages/uicore/src/components/TableV3/TableV3.tsx
Change:
Adding `className` dynamically to every row in the table.
Use case:
=> feat: [DBOPS-138]: Add getRowClassName to TableV3

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.css
=> feat: [STO-7995] MultiTypeInput dark mode fix

packages/uicore/package.json, packages/uicore/src/components/Accordion/Accordion.stories.tsx, packages/uicore/src/components/Accordion/Accordion.tsx, packages/uicore/src/index.ts
Adding 2 additional props in the accordion component
- allowOtherChildElem - To render other elements other than accordion children
- controlledActiveId - Now we can passed multiple active ID width controlled component. ease to use with combination of allowMultiOpen prop
=> feat: [PIPE-21132]: added support for allowOtherChildElem and multiple IDs in controlledActiveId

packages/uicore/src/_stories/typography.stories.mdx
The links in typography stories page did not work. Fixed by adding correct links
https://github.com/user-attachments/assets/51ad5a03-2013-48fc-a289-cd755e630d31
=> fix: [CDS-101106]: fix textual component links

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.css
=> fix: [PIPE-21956]: Make learn more popover border radius consistemt

packages/uicore/package.json, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.css, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.tsx, packages/uicore/src/components/Filters/components/FiltersMultiSelectDropDown/FiltersMultiSelectDropDown.tsx
When the dropdown is closed, we should not retain the search value
=> fix: [CDS-101412]: remove search value after popover close

packages/uicore/package.json, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.css, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.stories.tsx, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.tsx
Added section and section titles support in single select dropdown
=> feat: [CDS-101545]: add support for sections in dropdown

packages/uicore/package.json, packages/uicore/src/components/RadioButton/RadioButton.tsx, packages/uicore/src/components/RadioButton/RadioButtonGroup.tsx
=> fix: [CDS-98484]: add checked property to radio input along with defaultChecked

packages/uicore/package.json, packages/uicore/src/components/CodeBlock/CodeBlock.test.tsx, packages/uicore/src/components/CodeBlock/CodeBlock.tsx
Description:
There are use cases where, after copying a snippet, we need to display a toast message to confirm the action. To support this functionality, I’ve added a callback to the copy button in the CodeBlock component.
=> feat: [SEI-9257]: Added callbacks to copy button

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/custom-banner.svg
Added Custom banner icon from Figma ⬇️ 
=> feat: [PL-57105]: add icon for custom banners

packages/uicore/package.json, packages/uicore/src/components/ModalDialog/ModalDialog.tsx, packages/uicore/src/components/ScrollShadowContainer/ScrollShadowContainer.tsx, packages/uicore/src/components/Text/Text.css, packages/uicore/src/components/Text/Text.stories.tsx
**Issue:** React giving `Warning: React does not recognize the `bodyContentClassname` prop on a DOM element.`
**Fix:** Update class names props for ScrollShadowContainerProps to camelCase
=> fix: [PIPE-24105]: Warning: React does not recognize the  prop on a DOM element

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.stories.tsx, packages/uicore/src/components/Select/Select.stories.tsx, packages/uicore/src/components/Select/Select.tsx, packages/uicore/src/core/Utils.tsx
**Issue:** Select component always shows the tooltip if the `addTooltip` prop is true even if the selected item label element did not overflow.
**Fix:** Add tooltip when selected item label element overflow
**Before:**
https://github.com/user-attachments/assets/8d16fea0-05c4-42ba-b0e6-2d55b8d49831
**After:**
https://github.com/user-attachments/assets/284f0ea3-d6a6-44b5-9562-e939806665cf
**Uses in harness-core-ui:**
https://github.com/user-attachments/assets/f7f32350-70d5-4928-81bf-dba10b9f67af
- ImageSnapshot …
=> fix: [PIPE-20022]: Add support for tooltipProps for Select Component

packages/uicore/package.json, packages/uicore/src/components/CategorizedSelected/CategorizedSelect.stories.tsx, packages/uicore/src/components/FieldArray/Examples/FieldArrayExample.tsx, packages/uicore/src/components/ListHeader/ListHeader.stories.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.stories.tsx, packages/uicore/src/components/Select/Select.css, packages/uicore/src/components/Select/Select.tsx, packages/uicore/src/components/SelectWithSubview/SelectWithSubView.stories.tsx, packages/uicore/src/components/Table/Table.stories.tsx
=> fix: [PIPE-20022]: Fix MultiTypeInput Select value field with overlap label

packages/uicore/package.json, packages/uicore/src/components/Select/Select.stories.tsx, packages/uicore/src/components/Select/Select.tsx
**Before:**: Tooltip is not shown when selected value is updated
https://github.com/user-attachments/assets/094f4e66-e061-4b86-a09d-ca4382c2129d
**After:** Tootip shown when selected value change
https://github.com/user-attachments/assets/4accccae-5df8-499a-b010-c7bf90263e16
**Uses in harness-core-ui:**
https://github.com/user-attachments/assets/ca5d3ea6-87f0-49d0-b185-cce1241b25ea
=> fix: [PIPE-23362]: Show tooltip for the select when selected value change
