src/components/TableV2/TableV2.css, src/components/TableV2/TableV2.tsx
=> fix: [GIT-536]: text overflow in sync status table cell - Revert

src/components/ThumbnailSelect/ThumbnailSelect.tsx
=> feat: [PIE-2620]: Add expandAllByDefault option

src/styles/modal.css
=> fix: [PL-23065]: undo universal "dialog-size fixing".

src/components/FormError/FormError.tsx
=> feat: [CDS-25448]: Added element as an acceptable prop in FormError

src/components/FormError/FormError.tsx
=> fix: [CDS-25448]: CHanged element to jsx.element

src/components/InputWithIdentifier/InputWithIdentifier.tsx
=> fix: [PIE-2241]: Update labels of Identifier

src/index.ts
Exporting component added in https://github.com/harness/uicore/pull/622/files
=> feat: [CI-3613]: Exporting `MultiStepProgressIndicator` component

src/components/StackedSummaryTable/StackedSummaryTable.css
=> fix: [PIe-1808]: Add padding to StackSummaryTable

scripts/github-package-registry.sh
https://harness.atlassian.net/browse/SRM-10130
=> fix: [SRM-10130]: fix setup script

src/icons/HarnessIcons.ts, src/icons/slider-trigger.svg
=> feat: Add slider-trigger icon

package.json, src/components/CollapsableSelect/CollapsableSelect.test.tsx, src/components/CollapsableSelect/CollapsableSelect.tsx, src/components/CollapsableSelect/__snapshots__/CollapsableSelect.test.tsx.snap, src/components/FieldArray/FieldArray.tsx, src/components/FormError/FormError.tsx, src/components/FormikForm/FormikForm.tsx, src/components/FormikForm/__tests__/__snapshots__/FormikForm.test.tsx.snap, src/components/FormikForm/utils.tsx, src/components/GroupedThumbnailSelect/GroupedThumbnailSelect.tsx, src/components/InputWithIdentifier/InputWithIdentifier.tsx, src/components/ThumbnailSelect/ThumbnailSelect.tsx, src/core/Utils.tsx, yarn.lock
=> feat: [PIE-2618]: Formik Upgrade - April 27

src/components/MultiTypeInput/MultiTypeInput.tsx, src/components/Select/Select.css, src/components/Select/Select.tsx
JIRA - https://harness.atlassian.net/browse/PIE-2699
Before:
https://user-images.githubusercontent.com/96711906/158131566-4ecb678b-6f5f-48d1-9da4-e5f5a569e93b.mov
After:
https://user-images.githubusercontent.com/96711906/158131802-3d7c7e76-5ed3-4474-af07-3ab63cceaf79.mov
=> fix: [PIE-2699]: select popover portal css

README.md, package.json
=> chore: bump to v3

README.md, src/components/FormikForm/FormikForm.tsx
=> fix: TS issue in FormikForm

packages/icons/package.json
=> fix: [PL-22282]: Icons version bump

src/index.ts
This PR exports the `ModalDialog` component in the UICore package index file.
Refs [PL-25480](https://harness.atlassian.net/browse/PL-25480)
=> chore: [PL-25480]: Publish ModalDialog component

package.json
This PR bumps the version number. That is all. Carry on
=> chore: [PL-25480] Bump version number

package.json
=> feat: [PIE-3563]: version bump

package.json
=> chore: [PIE-3711]: Version bump

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
=> fix: [PL-24968]: should clear false values

src/components/Select/Select.tsx
=> fix: [PL-24968]: select clear button fixes

packages/help-panel/package.json, packages/help-panel/src/components/Article/Article.tsx
=> feat: [PL-25655]: Open help panel links in new tab

packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/components/SelectWithSubmenu/SelectWithSubmenu.css, packages/uicore/src/components/SelectWithSubmenu/SelectWithSubmenu.tsx, packages/uicore/src/index.ts
=> feat: [CDS-36921]: select with sub menu

packages/uicore/webpack.config.js
=> fix: types generation issue in uicore

packages/design-system/package.json, packages/help-panel/package.json, packages/help-panel/src/HelpPanelContext.tsx, packages/help-panel/src/components/HelpPanel/Containers/DefaultContainer/DefaultContainer.tsx, packages/help-panel/src/components/HelpPanel/Containers/FloatingContainer/FloatingContainer.module.css, packages/help-panel/src/components/HelpPanel/Containers/FloatingContainer/FloatingContainer.tsx, packages/help-panel/src/components/HelpPanel/Footer/Footer.tsx, packages/help-panel/src/components/HelpPanel/HelpPanel.tsx, packages/help-panel/src/components/HelpPanel/HelpPanelContent/HelpPanelContent.tsx
=> feat: [PL-25757]: Help Panel bugs fixes and changed exports in package json

packages/icons/src/HarnessIcons.ts
=> fix: icon names

packages/uicore/src/components/Accordion/Accordion.stories.tsx, packages/uicore/src/components/Accordion/Accordion.tsx
=> feat: add onChange on Accordion

packages/uicore/src/components/Accordion/Accordion.css, packages/uicore/src/components/Accordion/Accordion.stories.tsx, packages/uicore/src/components/Accordion/Accordion.tsx
=> feat: add disabled state in accordion panel and css cleanup

packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/components/SelectWithSubmenu/SelectWithSubmenu.css, packages/uicore/src/components/SelectWithSubmenu/SelectWithSubmenu.tsx
=> feat: [CDS-38779]: add clear button to select with sub menu

packages/icons/src/service-vm.svg
=> feat: [CI-4630]: optimize vm icon

packages/uicore/src/components/FormikForm/FormikForm.tsx
=> fix: [PIE-4185]: value added to selectwithsubmenu

packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/MultiSelectWithSubmenu/MultiSelectWithSubmenu.css, packages/uicore/src/components/MultiSelectWithSubmenu/MultiSelectWithSubmenu.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/index.ts
https://user-images.githubusercontent.com/96711906/175451117-5c26ecc2-07e9-44de-beb1-2532a33ffc69.mov
=> feat: [CDS-38779]: sub menu with multi select

packages/icons/src/Options.svg
Updated the Options button as apart of UX standardisation
=> feat: [FFM-3966]: update options button

packages/uicore/src/components/TableV2/TableV2.tsx
=> fix: [PIE-4356] move getRowClassName, testid to parent so existing tables won't break

packages/help-panel/src/components/HelpPanel/ErrorScreen/ErrorScreen.tsx
=> feat: [PL-26404]: Changed docs url in help panel

packages/uicore/src/components/StackedSummaryTable/StackedSummaryTable.css
=> fix: alignment in StackedSummaryTable

packages/uicore/src/components/MultiTypeInput/LearnMorePopover.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInputMenu.tsx, packages/uicore/src/components/MultiTypeInput/MultiTypeInputUtils.ts, packages/uicore/src/index.ts
=> feat: add a new type in multitype input

packages/icons/package.json
=> @harness/icons version 1.42.0

packages/icons/package.json
=> feat: [CCM-8226]: Upgraded icons version

packages/icons/package.json
=> feat: [CI-4835]: bump icon version

packages/uicore/package.json
=> fix: version bump

packages/uicore/package.json, packages/uicore/src/components/Tabs/Tabs.tsx
=> fix: [CDS-41744]: hide tab if hidden prop passed

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/grid.svg
=> feat: [SPG-155]: added grid icon

packages/help-panel/package.json, packages/help-panel/src/HelpPanelContext.tsx, packages/help-panel/src/index.ts
=> feat: [PL-27838]: export help panel storage key

packages/uicore/src/components/RadioButton/RadioButton.css, packages/uicore/src/components/RadioButton/RadioButton.tsx, packages/uicore/src/components/RadioButton/RadioButtonGroup.stories.tsx, packages/uicore/src/components/RadioButton/RadioButtonGroup.tsx
=> feat: [CI-5326]: add basic pill radio button css

packages/uicore/package.json
=> feat: [CI-5326]: up version number

README.md, packages/icons/package.json
- Updated Readme to add context for `uicore/icons` package bump in order to auto publish packages
- Bumped up package version for `uicore/icons` because I missed it in #822 
Signed-off-by: Sahil <sahil@harness.io>
=> fix: [CHAOS-285]: updated readme and bumped up uicore/icons package version

packages/uicore/package.json, packages/uicore/src/components/Carousel/Carousel.tsx
=> feat: [SPG-155]: slide and indicator class from props in Carousel component

packages/uicore/package.json, packages/uicore/src/components/ConfirmDialog/ConfirmationDialog.tsx
=> feat: [PIE-5424]: added intent in confirmation dialog

packages/uicore/package.json, packages/uicore/src/components/StepWizard/StepWizard.stories.tsx, packages/uicore/src/components/StepWizard/StepWizard.tsx, packages/uicore/src/components/StepWizard/example/StepWizardExample.tsx
=> fix: [PIE-5800]: Fixed StepWizard issues with dynamic steps

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.tsx
=> feat: [PL-28716]: persist query by passing it down to blueprint's Select

packages/icons/package.json
=> feat: [STO-4898]: Update semantic version for new STO icons

packages/uicore/src/components/Button/Button.tsx
=> feat: [PIE-5932]: Add support of aria-label on Buttons

packages/uicore/package.json
=> feat: [PIE-5932]: Increment version for aria-label

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/service-ami.svg
=> fix: [CDS-45972]: ami icon added and version bump

packages/icons/package.json
=> fix: [CDS-45972]: new ami icon version bump

packages/uicore/package.json, packages/uicore/src/components/Toggle/Toggle.tsx
=> feat: [CDS-45996]: add tooltip for toggle

packages/icons/package.json, packages/uicore/package.json, packages/uicore/src/components/AvatarGroup/AvatarGroup.tsx
=> feat: [PL-27564]: avatar classname and icon version bump

packages/uicore/package.json, packages/uicore/src/components/StepWizard/StepWizard.css
Revering back [recent changes](https://github.com/harness/uicore/pull/879/files ) done as it is creating regression : https://harness.atlassian.net/browse/PL-29850
=> fix: [PL-29850]: Fixing scroll issue in step wizard

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/arrow-down.svg
=> feat: [SPG-538]: Removed arrow-down icon

packages/uicore/package.json, packages/uicore/src/components/Page/PageBody.tsx, packages/uicore/src/components/Page/PageError.tsx, packages/uicore/src/components/Page/PageHeader.tsx, packages/uicore/src/components/Page/PageSpinner.tsx, packages/uicore/src/components/Page/PageSubHeader.tsx, packages/uicore/src/components/Page/__tests__/__snapshots__/PageError.test.tsx.snap, packages/uicore/src/components/Page/__tests__/__snapshots__/PageSubHeader.test.tsx.snap
=> feat: [CDS-47456]: add testids to page components for ease of access in automation, tests

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
=> fix: [PIE-6953]: Allow resetOnSelect to be passed from Parent

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/sscs-main.svg
=> feat: [PIE-6618]: sscs main icon

packages/uicore/package.json, packages/uicore/src/components/Thumbnail/Thumbnail.tsx, packages/uicore/src/components/ThumbnailSelect/ThumbnailSelect.tsx
=> feat: [CDS-47282]: label as ReactElement for ThumbnailSelect component

packages/uicore/package.json
Main PR: https://github.com/harness/uicore/pull/926
=> feat: [PL-30311]: version bump for changes in Avatar Component

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
JIRA - https://harness.atlassian.net/browse/PL-28172
=> fix: [PL-28172]: Removed onBlur from Multiselect

packages/uicore/package.json
=> feat: [PL-30704]: Uicore version bump

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
JIRA - https://harness.atlassian.net/browse/PL-30213
=> feat: [PL-30213]: Adding items on blur in Multiselect component

packages/uicore/package.json, packages/uicore/src/components/DropDown/DropDown.stories.tsx, packages/uicore/src/components/DropDown/DropDown.tsx
Also updated stories to have real search scenario
=> fix: [PIE-7606]: dropdown filter to work on search query change

packages/icons/package.json
=> feat: [STO-5411]: publish sto -inverse icons

packages/uicore/package.json
=> feat: Increase uicore version

packages/uicore/package.json, packages/uicore/src/components/ThumbnailSelect/ThumbnailSelect.stories.tsx, packages/uicore/src/components/ThumbnailSelect/ThumbnailSelect.tsx
=> feat: [CI-6489]: Add static items prop to thumbnail select to always show all options

packages/uicore/package.json
=> feat: [CI-6489]: bump version to force release

packages/uicore/package.json, packages/uicore/src/components/InputWithIdentifier/InputWithIdentifier.tsx
=> feat: [PL-31099]: increase name length to 128

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
=> feat: [PL-29630]: Added support for comma separated string in MultiSelect

docs/pages/minmaxslider.mdx, packages/uicore/package.json, packages/uicore/src/components/MinMaxSlider/MinMaxSlider.css, packages/uicore/src/components/MinMaxSlider/MinMaxSlider.stories.tsx, packages/uicore/src/components/MinMaxSlider/MinMaxSlider.test.tsx, packages/uicore/src/components/MinMaxSlider/MinMaxSlider.tsx, packages/uicore/src/index.ts
=> fix: [PL-31886]: Add MinMaxSlider component to UI Core library

packages/uicore/package.json, packages/uicore/src/components/MultiSelect/MultiSelect.tsx
=> feat: [PL-29630]: Added onItemsPaste in multiselect

packages/uicore/package.json
=> chore: [STO-5670]: Bump uicore package version

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx
=> fix: promise void return type added for formik onsubmit

packages/uicore/package.json, packages/uicore/src/components/SortDropdown/SortDropdown.tsx
=> feat: [PL-31535]: Added LastUpdatedDesc in SortDropdown

packages/icons/package.json
=> feat: [CET-1211]: Update icons package version.

packages/uicore/package.json
Version bump for changes in https://github.com/harness/uicore/pull/1032
=> chore: [PIE-9697]: Version bump

packages/uicore/package.json, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.css
https://user-images.githubusercontent.com/106532291/233575003-f1c65b6f-6800-4e31-812e-1c66645a4123.mov
=> fix: [PIE-9634]: fix expression component css

packages/uicore/package.json, packages/uicore/src/components/SortDropdown/SortDropdown.tsx
=> feat: [PL-31528]: add delegate sorting enums

packages/uicore/package.json, packages/uicore/src/index.ts
=> feat: Export stringSubstitute

packages/icons/package.json
=> feat: [OIP-408]: Update icons package version

packages/uicore/package.json, packages/uicore/src/components/Avatar/Avatar.tsx
=> feat: [PL-38892]: added usePortal as an optional prop to <Avatar /> component

packages/icons/package.json
=> feat: [code-288]: bump package

packages/uicore/package.json, packages/uicore/src/hooks/useToaster/useToaster.tsx
=> feat: [PL-32524]: swap error and warning icons

packages/uicore/package.json
=> feat: [CI-8243]: `uicore` version bump for PR#1079

packages/design-system/package.json, packages/design-system/src/styled-props/background.css
Reverting PR: https://github.com/harness/uicore/pull/1096
=> fix: [CI-8191]: Revert PR 1096

packages/icons/package.json
=> fix: [PL-39421]: Icons version bump

packages/design-system/LICENSE, packages/design-system/LICENSE.md, packages/design-system/package.json
=> fix: [CHAOS-1186]: bumped design system version for license update

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/download-box.svg
=> feat: [CDS-72603]: added download icon

packages/uicore/package.json, packages/uicore/src/components/AvatarGroup/AvatarGroup.tsx
=> chore: [CDS-76606]: added props to hide the add icon/option in Avatar group

packages/uicore/src/components/Breadcrumbs/Breadcrumbs.css, packages/uicore/src/components/Breadcrumbs/Breadcrumbs.tsx
=> fix breadcrumb styles

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/iacm-resource-unchanged.svg
=> feat: [IAC-1119]: Add unchanged icon

packages/uicore/package.json, packages/uicore/src/components/FormikForm/FormikForm.tsx, packages/uicore/src/components/FormikForm/__tests__/FormikForm.test.tsx, yarn.lock
This updates the KVTagInput to render a popover containing the `Create ${tag}` menu item. This improves the UX by letting the users know a tag is created only after pressing enter or clicking the `Create ${tag}` item.
https://github.com/harness/uicore/assets/52284933/8be47918-a0c9-4d47-9b42-d46ae70d29d5
=> feat: [CDS-78994]: Update KVTagInput to show create tag popover

packages/uicore/package.json
=> fix: [PL-42962]: version bump

packages/icons/src/HarnessIcons.ts
=> fix HarnessIcons file

packages/uicore/package.json, packages/uicore/src/components/TextAreaEditable/TextAreaEditable.tsx
=> fix: [CDS-88707]: typecase boolean values to string before serializing

packages/uicore/package.json, packages/uicore/src/components/Button/Button.tsx, packages/uicore/src/components/Text/Text.tsx, packages/uicore/src/components/Thumbnail/Thumbnail.tsx, packages/uicore/src/components/ThumbnailSelect/ThumbnailSelect.tsx
=> fix: fixed ttype issues

packages/uicore/package.json, packages/uicore/src/components/Avatar/Avatar.tsx
=> fix: [CDS-91069]: add border width support for avatar

packages/uicore/package.json
Bump version for this PR: https://github.com/harness/uicore/pull/1250
=> fix: [PL-48009]: bump uicore version

packages/uicore/package.json, packages/uicore/webpack.config.js
=> fix: [CDS-91153]: Fix CSS naming conflict between UICore v3 and v4

packages/uicore/package.json, packages/uicore/webpack.config.js
=> feat: Increase UICore version to 4.0.0-beta.12

packages/uicore/package.json
=> feat: Publish V4 to 4.0.0-beta.13

packages/icons/package.json
=> chore: Bump package version

packages/uicore/package.json
=> fix: [PL-48492]: bumped version

packages/uicore/package.json, packages/uicore/webpack.config.js
=> fix: [CODE-1656]: fix for uicoreV3 and V4 conflicting css names

packages/uicore/package.json, packages/uicore/src/components/Page/PageHeader.tsx
=> fix: [CDS-93678]: add titleContainerClassName to page header

packages/icons/package.json
=> feat: [SSCA-1645] uptick version for previous icons update

packages/icons/package.json
=> feat: Bumped up package version

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/suggestion.svg
=> feat: Add suggestion icon

packages/icons/package.json, packages/icons/src/HarnessIcons.ts, packages/icons/src/db-step.svg
=> feat: [DBOPS-135]: Added DB Step icon

packages/icons/package.json
=> chore: version update

packages/uicore/package.json, packages/uicore/src/frameworks/Tooltip/Tooltip.css, packages/uicore/src/frameworks/Tooltip/Tooltip.tsx
=> feat: [CDS-98142]: use native dark tooltips

packages/uicore/package.json, packages/uicore/src/components/ExpressionInput/ExpressionInput.css, packages/uicore/src/components/ExpressionInput/ExpressionInput.tsx, packages/uicore/src/components/ExpressionInput/__tests__/__snapshots__/ExpressionInput.test.tsx.snap, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.css, packages/uicore/src/components/Pagination/Pagination.css, packages/uicore/src/components/Pagination/Pagination.tsx
Issues:
| Light | Dark |
| ------ | ------ |
| <img width="761" alt="image" src="https://github.com/user-attachments/assets/9b26559b-e6da-4a54-9ca9-abe2dd3d486e">| <img width="761" alt="image" src="https://github.com/user-attachments/assets/50a5e731-81b9-49df-89a3-6fb0ffdc0730">|
| <img width="593" alt="image" src="https://github.com/user-attachments/assets/2d09ec75-c11a-437d-970e-091b328f74d8">| <img width="593" alt="image" src="https://github.com/user-attachments/assets/901c9cf1-e86c-41bd-a576-9a1cb4108666"> |
|<img width="668" alt="image" src="https://github.com/user-attachments/assets/1f53a2ca-eb6c-4008-bd21-19191454160d"> |<img width="668" alt="image" src="https://github.com/user-attachments/assets/72d536d6-2168-4069-867f-965cd61fbccf">|
You can use the following comments to …
=> fix: [CDS-98905]: fix css for dark theme

packages/uicore/package.json, packages/uicore/src/components/Pagination/Pagination.tsx
Pass Pagination action to the callback function to use it for telemetry event
=> feat: [PIPE-20778]: Pass action name on Pagination callback for tracking

packages/icons/package.json
=> feat: [DBOPS-320]: Bump up icons version for rollback icon add

packages/uicore/package.json, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.tsx, packages/uicore/src/components/Filters/components/FilterTextInput/FilterTextInput.tsx, packages/uicore/src/components/Filters/components/FiltersMultiSelectDropDown/FiltersMultiSelectDropDown.tsx
=> feat: [CDS-100181]: filter component fixes

packages/icons/package.json
=> feat: [CCM-19301]: version upgrade

packages/icons/package.json, packages/icons/src/ssca-ruledefinition.svg
The following change is required as the icon was not getting highlighted in the sidenav, so have set the stroke property to currentColor.
=> feat: [SSCA-2562]: Updating the rule definition icon.

packages/uicore/package.json, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.css, packages/uicore/src/components/Filters/components/FilterSingleSelectDropDown/FiltersSelectDropDown.tsx, packages/uicore/src/components/Filters/components/FilterTextInput/FilterTextInput.css, packages/uicore/src/components/Filters/components/FilterTextInput/FilterTextInput.tsx, packages/uicore/src/components/Filters/components/FiltersMultiSelectDropDown/FiltersMultiSelectDropDown.css, packages/uicore/src/components/Filters/components/FiltersMultiSelectDropDown/FiltersMultiSelectDropDown.tsx
=> fix: [CDS-100515]: filters UX fixes

packages/uicore/package.json, packages/uicore/src/components/MultiTypeInput/MultiTypeInput.css
=> feat: [STO-8092]: Reverting changes to fix core-ui snapshots

packages/icons/package.json
=> fix: [IDP-4222]: IDP Homepage icons

packages/uicore/package.json, packages/uicore/src/components/Select/Select.tsx
=> feat: [PIPE-20022]: Add support for Select tooltip position
